version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: alma_digitales_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/webhook
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - N8N_ENCRYPTION_KEY=alma_digitales_2024_secure_key
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
